### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by puhitaku** [puhitaku/naam#3]
Re-opened.

 - [ ] Type casting with type hints
 - [ ] Verbose usage `--help`
 - [ ] Parse docstring
 - [ ] Flags (args without value like `--enable_foo --enable_bar`)
 - [ ] Subcommands (low priority)
 - [ ] More abbreviation patterns (e.g. `-ef` for `--enable_foo`)
